using System;
using System.Collections.Generic;

#nullable disable

namespace KuberMICManager.Core.Domain.Entities
{
    public partial class TdsLoan
    {
        public string RecId { get; set; }
        public string BorrowerRecId { get; set; }
        public string Account { get; set; }
        public string SortName { get; set; }
        public string ByLastName { get; set; }
        public string FullName { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string Mi { get; set; }
        public string LastName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneWork { get; set; }
        public string PhoneCell { get; set; }
        public string PhoneFax { get; set; }
        public int? PhoneMain { get; set; }
        public string Tin { get; set; }
        public int? Tintype { get; set; }
        public decimal? OrigBal { get; set; }
        public decimal? PrinBal { get; set; }
        public decimal? FundControl { get; set; }
        public decimal? UnearnedDisc { get; set; }
        public int? DiscRecapMethod { get; set; }
        public decimal? NoteRate { get; set; }
        public decimal? SoldRate { get; set; }
        public bool? UseSoldRate { get; set; }
        public decimal? UnpaidLateCharges { get; set; }
        public decimal? UnpaidInterest { get; set; }
        public int? UnpaidIntRateType { get; set; }
        public decimal? UnpaidIntRateValue { get; set; }
        public decimal? PmtPi { get; set; }
        public decimal? PmtReserve { get; set; }
        public decimal? PmtImpound { get; set; }
        public DateTime? ClosingDate { get; set; }
        public DateTime? FirstPaymentDate { get; set; }
        public DateTime? PaidToDate { get; set; }
        public DateTime? NextDueDate { get; set; }
        public DateTime? MaturityDate { get; set; }
        public DateTime? PaidOffDate { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public DateTime? BookingDate { get; set; }
        public DateTime? NextRevision { get; set; }
        public int? Priority { get; set; }
        public string PmtFreq { get; set; }
        public int? DueDay { get; set; }
        public int? LoanType { get; set; }
        public int? AmortType { get; set; }
        public int? RateType { get; set; }
        public bool? Section32 { get; set; }
        public bool? Respa { get; set; }
        public bool? Article7 { get; set; }
        public bool? Section4970 { get; set; }
        public int? AccrualMethod { get; set; }
        public bool? NegAmortToInterest { get; set; }
        public bool? UseUnpaidInterest { get; set; }
        public bool? Use30DayMonths { get; set; }
        public bool? Use365DailyRate { get; set; }
        public bool? AutoPayUnpaidInterest { get; set; }
        public bool? CanadianAmortization { get; set; }
        public int? PrepayMon { get; set; }
        public decimal? PrepayPct { get; set; }
        public int? PrepayFrom { get; set; }
        public DateTime? PrepayExp { get; set; }
        public int? PrepayTest { get; set; }
        public decimal? PrepayLenderPct { get; set; }
        public decimal? PrepayVendorPct { get; set; }
        public int? PrepaymentPenalty { get; set; }
        public string PrepayOtherRecId { get; set; }
        public int? LateChgMethod { get; set; }
        public int? LateChgDays { get; set; }
        public decimal? LateChgMin { get; set; }
        public int? LateChgPctOf { get; set; }
        public decimal? LateChgPct { get; set; }
        public decimal? LateChgLenderPct { get; set; }
        public decimal? LateChgVendorPct { get; set; }
        public decimal? LateChgDaily { get; set; }
        public int? GraceDaysMethod { get; set; }
        public string LoanOfficer { get; set; }
        public string LoanCode { get; set; }
        public string Categories { get; set; }
        public string OrigVendorRecId { get; set; }
        public bool? Send1098 { get; set; }
        public decimal? PointsPaid1098 { get; set; }
        public bool? SendLateNotices { get; set; }
        public bool? SendPaymentReceipt { get; set; }
        public bool? SendPaymentStatement { get; set; }
        public string EmailAddress { get; set; }
        public int? EmailFormat { get; set; }
        public int? DeliveryOptions { get; set; }
        public bool? PlaceOnHold { get; set; }
        public int? RolodexFlag { get; set; }
        public bool? PostMaturity { get; set; }
        public int? DretransType { get; set; }
        public decimal? DresellingPrice { get; set; }
        public decimal? DrecommissionReceived { get; set; }
        public decimal? DrecostsBorrowerPaid { get; set; }
        public decimal? DrecostsBrokerRetained { get; set; }
        public decimal? DrenotePurchasePrice { get; set; }
        public decimal? DrenoteSellingPrice { get; set; }
        public bool? DrerefinanceBrokerLoan { get; set; }
        public bool? DrebrokerFundedLoanResale { get; set; }
        public string DrenoteHolder { get; set; }
        public decimal? DrefundsAdvanced { get; set; }
        public decimal? DreappraisalFees { get; set; }
        public decimal? DretitleFees { get; set; }
        public decimal? DreoriginationCharges { get; set; }
        public bool? DrenonTraditionalLoan { get; set; }
        public int? Drelanguage { get; set; }
        public string LoanPurpose { get; set; }
        public string Documentation { get; set; }
        public int? Fico { get; set; }
        public bool? EscrowStatementSend { get; set; }
        public DateTime? EscrowStatementNext { get; set; }
        public string WpcPin { get; set; }
        public bool? WpcPublish { get; set; }
        public string AchBankName { get; set; }
        public string AchBankAddress { get; set; }
        public string AchRoutingNumber { get; set; }
        public string AchAccountNumber { get; set; }
        public string AchIndividualId { get; set; }
        public string AchIndividualName { get; set; }
        public int? AchAccountType { get; set; }
        public int? AchServiceStatus { get; set; }
        public decimal? AchDebitAmount { get; set; }
        public DateTime? AchStopDate { get; set; }
        public int? AchDebitDueDay { get; set; }
        public DateTime? AchNextDebitDate { get; set; }
        public int? AchFrequency { get; set; }
        public int? AchApplyAs { get; set; }
        public bool? AchUseDebitAmount { get; set; }
        public string ArmIndexRecId { get; set; }
        public decimal? ArmIndexRate { get; set; }
        public decimal? ArmMargin { get; set; }
        public decimal? ArmCeiling { get; set; }
        public decimal? ArmFloor { get; set; }
        public bool? ArmRateFirstChgActive { get; set; }
        public decimal? ArmRateFirstChgMinCap { get; set; }
        public decimal? ArmRateFirstChgMaxCap { get; set; }
        public decimal? ArmRatePeriodicMinCap { get; set; }
        public decimal? ArmRatePeriodicMaxCap { get; set; }
        public int? ArmRateChangeFreq { get; set; }
        public DateTime? ArmRateChangeNext { get; set; }
        public int? ArmRateRounding { get; set; }
        public decimal? ArmRateRoundFactor { get; set; }
        public bool? ArmSendRateChangeNotice { get; set; }
        public int? ArmNoticeLeadDays { get; set; }
        public bool? ArmCarryoverEnabled { get; set; }
        public decimal? ArmCarryoverAmount { get; set; }
        public int? ArmLookBackDays { get; set; }
        public bool? ArmPaymentAdjustment { get; set; }
        public decimal? ArmPaymentCap { get; set; }
        public int? ArmPaymentChangeFreq { get; set; }
        public DateTime? ArmPaymentChangeNext { get; set; }
        public decimal? ArmNegAmortCap { get; set; }
        public bool? ArmRecastPayment { get; set; }
        public int? ArmRecastFreq { get; set; }
        public DateTime? ArmRecastNextDate { get; set; }
        public DateTime? ArmRecastStopDate { get; set; }
        public DateTime? ArmRecastToDate { get; set; }
        public bool? ArmUseRecastToDate { get; set; }
        public bool? ArmIsOptionArm { get; set; }
        public DateTime? ArmFirstNoticeDate { get; set; }
        public int? LocDrawPeriod { get; set; }
        public decimal? LocDrawMinimum { get; set; }
        public decimal? LocDrawMaximum { get; set; }
        public bool? LocUseDrawMaximum { get; set; }
        public bool? LocUseDrawFee { get; set; }
        public decimal? LocDrawFeePct { get; set; }
        public decimal? LocDrawFeePlus { get; set; }
        public decimal? LocDrawFeeMin { get; set; }
        public int? LocRepaymentPeriod { get; set; }
        public decimal? LocCreditLimit { get; set; }
        public int? LocBillingFreq { get; set; }
        public DateTime? LocBilledToDate { get; set; }
        public int? LocBillingStartDay { get; set; }
        public bool? LocUseMaintenanceFee { get; set; }
        public decimal? LocMaintenanceFeeAmount { get; set; }
        public int? LocMaintenanceFeeFreq { get; set; }
        public DateTime? LocMaintenanceFeeNextDue { get; set; }
        public int? LocCalculationMethod { get; set; }
        public decimal? LocEarlyClosureAmount { get; set; }
        public int? LocEarlyClosureMonths { get; set; }
        public bool? LocExcludeFinanceCharges { get; set; }
        public bool? LocExcludeReserveBalances { get; set; }
        public bool? LocExcludeImpoundBalances { get; set; }
        public bool? LocExcludeLateCharges { get; set; }
        public int? LocPayAmountMethod { get; set; }
        public decimal? LocPayAmountValue { get; set; }
        public string ConProjectDescription { get; set; }
        public int? ConProjectSqft { get; set; }
        public DateTime? ConCompletionDate { get; set; }
        public decimal? ConConstructionLoan { get; set; }
        public string ConContractorRecId { get; set; }
        public string ConContractorLicNo { get; set; }
        public bool? ConJointCheck { get; set; }
        public bool? ConRevolving { get; set; }
        public bool? ConChargeIntOnAvailFunds { get; set; }
        public int? ConChargeIntOnAvailFundsMethods { get; set; }
        public decimal? ConChargeIntOnAvailFundsRate { get; set; }
        public bool? DefaultRateUse { get; set; }
        public int? DefaultRateAfterPeriod { get; set; }
        public int? DefaultRateAfterValue { get; set; }
        public int? DefaultRateUntil { get; set; }
        public int? DefaultRateMethod { get; set; }
        public decimal? DefaultRateValue { get; set; }
        public decimal? DefaultRateLenderPct { get; set; }
        public decimal? DefaultRateVendorPct { get; set; }
        public bool? AutoPayFromReserveUse { get; set; }
        public decimal? AutoPayFromReserveAmount { get; set; }
        public decimal? AutoPayFromReservePct { get; set; }
        public int? AutoPayFromReserveOverdrawnMethod { get; set; }
        public string LosloanRecId { get; set; }
        public bool? Cdfireporting { get; set; }
        public bool? IsTemplate { get; set; }
        public string Xml { get; set; }
        public DateTime? SysTimeStamp { get; set; }
        public int? SysRecStatus { get; set; }
        public string SysCreatedBy { get; set; }
        public DateTime? SysCreatedDate { get; set; }
        public bool? LocMaintenanceFeeAssessInt { get; set; }
        public bool? WpcDisableOnlinePmts { get; set; }
        public int? AchSeccode { get; set; }
        public bool? AchUseAddendaRecord { get; set; }
        public string AchAddendaRecord { get; set; }
        public string CompanyRecId { get; set; }
    }
}
