using System;
using System.Collections.Generic;

#nullable disable

namespace KuberMICManager.Core.Domain.Entities
{
    public partial class TdsOption
    {
        public string RecId { get; set; }
        public bool? ReportInterestLessFees { get; set; }
        public bool? ReportNetRatePayment { get; set; }
        public bool? AccrueInterestOnPayoffDate { get; set; }
        public bool? AccrueInterestOnChargesThroughToday { get; set; }
        public string TrustAccountRecId { get; set; }
        public bool? Gstuse { get; set; }
        public decimal? Gstrate { get; set; }
        public string GstvendorRecId { get; set; }
        public string LateNoticeName { get; set; }
        public bool? SendLateNotice1 { get; set; }
        public bool? SendLateNotice2 { get; set; }
        public bool? SendLateNotice3 { get; set; }
        public bool? SendLateNotice4 { get; set; }
        public int? LateNoticeDays1 { get; set; }
        public int? LateNoticeDays2 { get; set; }
        public int? LateNoticeDays3 { get; set; }
        public int? LateNoticeDays4 { get; set; }
        public int? LateNoticeAfter1 { get; set; }
        public int? LateNoticeAfter2 { get; set; }
        public int? LateNoticeAfter3 { get; set; }
        public int? LateNoticeAfter4 { get; set; }
        public decimal? Nsfcharge { get; set; }
        public bool? NsfdeleteChecks { get; set; }
        public string NsfnoticeName { get; set; }
        public string PayoffNoticeName { get; set; }
        public int? PayoffNoticeExpireDays { get; set; }
        public string PayoffNoticeFeeDesc1 { get; set; }
        public string PayoffNoticeFeeDesc2 { get; set; }
        public string PayoffNoticeFeeDesc3 { get; set; }
        public string PayoffNoticeFeeDesc4 { get; set; }
        public string PayoffNoticeFeeDesc5 { get; set; }
        public decimal? PayoffNoticeFeeAmt1 { get; set; }
        public decimal? PayoffNoticeFeeAmt2 { get; set; }
        public decimal? PayoffNoticeFeeAmt3 { get; set; }
        public decimal? PayoffNoticeFeeAmt4 { get; set; }
        public decimal? PayoffNoticeFeeAmt5 { get; set; }
        public string HudnoticeName { get; set; }
        public int? HudnoticeDays { get; set; }
        public string BalloonNoticeName { get; set; }
        public string BeneStatementName { get; set; }
        public string ReinstmtNoticeName { get; set; }
        public string ArmnoticeName { get; set; }
        public string Armrespa1noticeName { get; set; }
        public string Armrespa2noticeName { get; set; }
        public string GtmnoticeName { get; set; }
        public string InsExpNoticeName { get; set; }
        public bool? SendInsExpNotice1 { get; set; }
        public bool? SendInsExpNotice2 { get; set; }
        public bool? SendInsExpNotice3 { get; set; }
        public int? InsExpNoticeDays1 { get; set; }
        public int? InsExpNoticeDays2 { get; set; }
        public int? InsExpNoticeDays3 { get; set; }
        public bool? PrintLenderChecks { get; set; }
        public bool? PrintChargeNotesOnChecks { get; set; }
        public bool? PrintChargeDescOnChecks { get; set; }
        public bool? PrintDetailOnBrokerCheck { get; set; }
        public bool? PrintPortfolioYieldOnChecks { get; set; }
        public bool? PrintYtdInterestOnChecks { get; set; }
        public int? HoldCheckDays { get; set; }
        public int? HoldAchdays { get; set; }
        public int? CheckStyle { get; set; }
        public string CouponReturnAddress { get; set; }
        public string CouponBottomLeftBoxText { get; set; }
        public string CouponBottomRightBoxText { get; set; }
        public string ReceiptReturnAddress { get; set; }
        public string ReceiptBottomLeftBoxText { get; set; }
        public string ReceiptBottomRightBoxText { get; set; }
        public int? PaymentStatementStyle { get; set; }
        public string StatementReturnAddress { get; set; }
        public string StatementBottomLeftBoxText { get; set; }
        public string StatementBottomRightBoxText { get; set; }
        public byte[] CompanyLogo { get; set; }
        public bool? UseCompanyLogo { get; set; }
        public string LoanFilterCategory { get; set; }
        public bool? LoanFilterIsActive { get; set; }
        public string LenderFilterCategory { get; set; }
        public bool? LenderFilterIsActive { get; set; }
        public bool? ConprintCompanyOnCheck { get; set; }
        public string ContrustAccountRecId { get; set; }
        public bool? AutoPayGroupPayments { get; set; }
        public bool? AutoPayLateCharges { get; set; }
        public bool? AutoPayCharges { get; set; }
        public bool? AutoPayChargesAllOrNone { get; set; }
        public bool? AutoPayChargesCompanyFirst { get; set; }
        public bool? AutoPayExcessToPrincipal { get; set; }
        public bool? AutoPayShortPayment { get; set; }
        public bool? AutoPayShortPaymentPi { get; set; }
        public bool? AutoPayShortPaymentReserve { get; set; }
        public bool? AutoPayShortPaymentImpound { get; set; }
        public bool? AutoPayShortPaymentOtherPayments { get; set; }
        public bool? AutoPayShortPaymentAccruedLateCharge { get; set; }
        public bool? AutoPayShortPaymentUnpaidLateCharges { get; set; }
        public bool? AutoPayShortPaymentUnpaidCharges { get; set; }
        public bool? AutoPayShortPaymentUnpaidInterest { get; set; }
        public bool? AutoPayNegPrinBalToPrincipal { get; set; }
        public bool? AutoPayNegPrinBalToReserve { get; set; }
        public bool? AutoPayNegPrinBalToBorrower { get; set; }
        public bool? EscrowAnalysisExcludeBorrowersOnHold { get; set; }
        public bool? EscrowAnalysisExcludeLateBorrowers { get; set; }
        public bool? EscrowAnalysisExcludeBorrowersInForeclosure { get; set; }
        public int? EscrowAnalysisNumberOfPaymentsAsCushion { get; set; }
        public bool? EscrowAnalysisSurplusRefundToBorrower { get; set; }
        public bool? EscrowAnalysisShortageLessThanOnePaymentDoNothing { get; set; }
        public bool? EscrowAnalysisShortageLessThanOnePaymentRepayInThirtyDays { get; set; }
        public bool? EscrowAnalysisShortageLessThanOnePaymentRepayInAyear { get; set; }
        public bool? EscrowAnalysisShortageMoreThanOnePaymentDoNothing { get; set; }
        public bool? EscrowAnalysisShortageMoreThanOnePaymentRepay { get; set; }
        public bool? EscrowAnalysisDeficiencyLessThanOnePaymentDoNothing { get; set; }
        public bool? EscrowAnalysisDeficiencyLessThanOnePaymentRepayInThirtyDays { get; set; }
        public bool? EscrowAnalysisDeficiencyLessThanOnePaymentRepayInMonths { get; set; }
        public int? EscrowAnalysisDeficiencyLessThanOnePaymentNumberOfMonths { get; set; }
        public bool? EscrowAnalysisDeficiencyMoreThanOnePaymentDoNothing { get; set; }
        public bool? EscrowAnalysisDeficiencyMoreThanOnePaymentRepayInMonths { get; set; }
        public int? EscrowAnalysisDeficiencyMoreThanOnePaymentNumberOfMonths { get; set; }
        public bool? BorrAccountNumbering { get; set; }
        public string BorrAccountPrefix { get; set; }
        public int? BorrAccountNumber { get; set; }
        public string BorrAccountSuffix { get; set; }
        public int? BorrAccountDigits { get; set; }
        public bool? BorrAccountZeroFill { get; set; }
        public bool? LndrAccountNumbering { get; set; }
        public string LndrAccountPrefix { get; set; }
        public int? LndrAccountNumber { get; set; }
        public string LndrAccountSuffix { get; set; }
        public int? LndrAccountDigits { get; set; }
        public bool? LndrAccountZeroFill { get; set; }
        public bool? VndrAccountNumbering { get; set; }
        public string VndrAccountPrefix { get; set; }
        public int? VndrAccountNumber { get; set; }
        public string VndrAccountSuffix { get; set; }
        public int? VndrAccountDigits { get; set; }
        public bool? VndrAccountZeroFill { get; set; }
        public string CompanyRecId { get; set; }
    }
}
